#
#
#
# Plugin:
# This Plugin was created for the Minecraft Server TerraCraft (play.terracraft.fr)
# The goal is to propose a complete and fully editable plugin working on the lasts versions of Minecraft
# Concept: every time you set, a random number (you can desactivate this option) is generated, players haves to find the number,
# the first player who find the random number is the winner of the event, you can add/edit rewards
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#




#---------------------------------------------------------------------------------



findthenumberConfig:
  prefix: "&7&l[&6Find The Number&7&l]" #Plugin prefix
  delay: 60 #Time in minutes between to events
  messages:
    broadcasts:
      firstBroadcast: #Broadcast who announce the event
        # use dash to create a new line
        - "&7&n                             "
        - " "
        - " "
        - " "
        - "    &e&l⚡ &b&lPLAY.TERRACRAFT.FR &e&l⚡ "
        - " "
        - "&7➤ &b&lFind the number event !"
        - " "
        # Numbers %firstNumber% and %secondNumber% are differents according to online players number
        - "&6&llFind the number between %firstNumber% and %secondNumber%. The first person to discover it will be crowned the"
        - "&6&lultimate champion!"
        - " "
        - "&6&k!! &7&lGood lucks ! &6&k!!"
        - " "
      winningBroadast: # Broadcasted when a player has finded the number
        # use dash to create a new line
        - "&7&n                             "
        - " "
        - " "
        - " "
        - "    &e&l⚡ &b&lFind The Number Event &e&l⚡ "
        - " "
        - " &6&lThe player &7%winner% &6&lhad finded the number,"
        - " &6&lcongrulations to him !"
        - " "
        - "     &c&l❤ &b&lTERRACRAFT.FR &c&l❤  "